### ISSUE TITLE
Issues in the Geoquery dataset 

### ISSUE THREAD

**Issue by phuongnm94** [itayle/diverse-demonstrations#1]
The logic in column "target" of the GeoQuery dataset should NOT be anonymized, but it seems that have some problem in processing data that make the object name values anonymized and exactly the same as column "anonymized."

For examples: 
```
{"qid": "geo880_0", "source": "give me the cities in virginia", "target": "answer(city(loc_2(stateid('value'))))", "anonymized": "answer(city(loc_2(stateid('value'))))"}
{"qid": "geo880_1", "source": "what are the high points of states surrounding mississippi", "target": "answer(high_point_1(state(next_to_2(stateid('value')))))", "anonymized": "answer(high_point_1(state(next_to_2(stateid('value')))))"}
```

@itayle  Could you check it again and update the correct version? Thank you.

**Comment by itayle** [comment]
Hey there! Thanks for your comment

The entities in the target column of GeoQuery were anonymized on purpose. This is to ensure consistency with the targets used in previous works we compare against ([Improving Compositional Generalization with Latent Structure and Data Augmentation](https://arxiv.org/abs/2112.07610), [Evaluating the Impact of Model Scale for Compositional Generalization in Semantic Parsing](https://arxiv.org/abs/2205.12253)). I’m sorry we didn't stress this adequately in the paper.
